### ISSUE TITLE
Should CommitData::FileConflict carry OwnedFileConflict instead of OwnedConflict?

### ISSUE THREAD

**Issue by UhhhWaitWhat** [archlinux/alpm.rs#46]
Hi, so I finally got around to updating a project of mine to v3 of this library. I stumbled across the changes to `trans_commit`s return type, namely that I used to be able to get detailed data about file conflicts. Based on my previous usage, it *feels* like `CommitData::FileConflict` should carry an `OwnedFileConflict`, but it does not.

So I was wondering if this is a mistake on the libraries part or if I'm doing something wrong :)

**Comment by anrdnet** [comment]
I just ran into the need to parse `CommitData::FileConflict` errors, and was also stumped by this. Since I had a reproducible file conflict I did some tests. I can iterate through the `AlpmList`, but accessing the packages of the `OwnedConflict` results in `SIGSEGV`. This seems consistent with the element being accessed as the wrong type.
